### ISSUE TITLE
Can you publish this as a npm package?

### ISSUE THREAD

**Issue by vardhan2k8** [PatrickRoumanoff/js-keygen#2]
Hello,
I couldn't find this as an npm package. Is it possible to publish this as an npm package?

Thanks!
Ranga

**Comment by PatrickRoumanoff** [comment]
This is using the WebCrypto API which is not available in node, so no, I can't publish an npm package. there alternatives though, like https://github.com/anvilresearch/webcrypto

**Comment by mendhak** [comment]
It seems Node has now implemented WebCrypto API, this could be worth considering now? 

https://nodejs.org/api/webcrypto.html
