### ISSUE TITLE
inverse conversion

### ISSUE THREAD

**Issue by gossoudarev** [PatrickRoumanoff/js-keygen#3]
Hello Patrick! May I ask for a script for backward conversion from PEM to OpenSSH?

**Comment by PatrickRoumanoff** [comment]
The code to convert from PEM to openSSH is already in the code base, since webcrypto generates the PEM version and I added a bit of mangling to build up the openSSH version

**Comment by gossoudarev** [comment]
It must be just me being inattentive, so I couldn't locate it in the repository =(

**Comment by PatrickRoumanoff** [comment]
look into encodePublicKey at https://github.com/PatrickRoumanoff/js-keygen/blob/master/ssh-util.js#L85
